/**
 * Membership Management Handlers
 * 
 * These endpoints are called by the SkillPassport worker via service binding
 * to manage memberships in the SSO database. They require SERVICE_AUTH_SECRET.
 * 
 * Used for invitation acceptance flow where foreign tables cannot be written to.
 */

import { Env } from '../types';
import { createClient } from '@supabase/supabase-js';

/**
 * POST /api/memberships/create
 * Create a new membership record
 */
export async function createMembership(request: Request, env: Env): Promise<Response> {
    console.log('[createMembership] Request received');

    const supabase = createClient(env.SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

    let body: { user_id?: string; org_id?: string; status?: string };
    try {
        body = await request.json();
    } catch (error) {
        console.error('[createMembership] Failed to parse JSON:', error);
        return Response.json({ error: 'Invalid JSON body' }, { status: 400 });
    }

    const { user_id, org_id, status } = body;

    // Validate required fields
    if (!user_id || !org_id || !status) {
        console.error('[createMembership] Missing required fields:', {
            hasUserId: !!user_id,
            hasOrgId: !!org_id,
            hasStatus: !!status
        });
        return Response.json({
            error: 'Missing required fields',
            details: 'user_id, org_id, and status are required'
        }, { status: 400 });
    }

    console.log('[createMembership] Creating membership:', {
        user_id,
        org_id,
        status
    });

    // Create membership (note: memberships table doesn't have updated_at)
    const { data, error } = await supabase
        .from('memberships')
        .insert({
            user_id,
            org_id,
            status,
            // created_at is auto-generated by database DEFAULT now()
        })
        .select()
        .single();

    if (error) {
        console.error('[createMembership] Failed to create membership:', error);
        return Response.json({
            error: 'Failed to create membership',
            details: error.message
        }, { status: 500 });
    }

    console.log('[createMembership] ✓ Membership created:', data.id);
    return Response.json({
        id: data.id,
        status: data.status
    });
}

/**
 * PUT /api/memberships/update-status
 * Update membership status (e.g., reactivate inactive membership)
 */
export async function updateMembershipStatus(request: Request, env: Env): Promise<Response> {
    console.log('[updateMembershipStatus] Request received');

    const supabase = createClient(env.SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

    let body: { membership_id?: string; status?: string };
    try {
        body = await request.json();
    } catch (error) {
        console.error('[updateMembershipStatus] Failed to parse JSON:', error);
        return Response.json({ error: 'Invalid JSON body' }, { status: 400 });
    }

    const { membership_id, status } = body;

    // Validate required fields
    if (!membership_id || !status) {
        console.error('[updateMembershipStatus] Missing required fields:', {
            hasMembershipId: !!membership_id,
            hasStatus: !!status
        });
        return Response.json({
            error: 'Missing required fields',
            details: 'membership_id and status are required'
        }, { status: 400 });
    }

    console.log('[updateMembershipStatus] Updating membership:', {
        membership_id,
        status
    });

    // Update membership (note: memberships table doesn't have updated_at)
    const { error } = await supabase
        .from('memberships')
        .update({
            status,
        })
        .eq('id', membership_id);

    if (error) {
        console.error('[updateMembershipStatus] Failed to update membership status:', error);
        return Response.json({
            error: 'Failed to update membership status',
            details: error.message
        }, { status: 500 });
    }

    console.log('[updateMembershipStatus] ✓ Membership status updated');
    return Response.json({ success: true });
}

/**
 * POST /api/memberships/assign-role
 * Assign a role to a membership
 */
export async function assignMembershipRole(request: Request, env: Env): Promise<Response> {
    console.log('[assignMembershipRole] Request received');

    const supabase = createClient(env.SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

    let body: { membership_id?: string; role_id?: string };
    try {
        body = await request.json();
    } catch (error) {
        console.error('[assignMembershipRole] Failed to parse JSON:', error);
        return Response.json({ error: 'Invalid JSON body' }, { status: 400 });
    }

    const { membership_id, role_id } = body;

    // Validate required fields
    if (!membership_id || !role_id) {
        console.error('[assignMembershipRole] Missing required fields:', {
            hasMembershipId: !!membership_id,
            hasRoleId: !!role_id
        });
        return Response.json({
            error: 'Missing required fields',
            details: 'membership_id and role_id are required'
        }, { status: 400 });
    }

    console.log('[assignMembershipRole] Assigning role:', {
        membership_id,
        role_id
    });

    // Check if already assigned (avoid duplicate constraint error)
    const { data: existing, error: checkError } = await supabase
        .from('membership_roles')
        .select('id')
        .eq('membership_id', membership_id)
        .eq('role_id', role_id)
        .maybeSingle();

    if (checkError) {
        console.error('[assignMembershipRole] Error checking existing role:', checkError);
        return Response.json({
            error: 'Failed to check existing role',
            details: checkError.message
        }, { status: 500 });
    }

    if (existing) {
        console.log('[assignMembershipRole] ✓ Role already assigned');
        return Response.json({ success: true });
    }

    // Create new assignment (note: membership_roles table doesn't have updated_at)
    const { error: insertError } = await supabase
        .from('membership_roles')
        .insert({
            membership_id,
            role_id,
            // created_at is auto-generated by database DEFAULT now()
        });

    if (insertError) {
        console.error('[assignMembershipRole] Failed to assign role:', insertError);
        return Response.json({
            error: 'Failed to assign role',
            details: insertError.message
        }, { status: 500 });
    }

    console.log('[assignMembershipRole] ✓ Role assigned successfully');
    return Response.json({ success: true });
}
